"""V3 unit aded to quantity  

Revision ID: b1c317dc7fd4
Revises: 421ccd8d7753
Create Date: 2026-07-09 15:25:35.234185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1c317dc7fd4'
down_revision: Union[str, Sequence[str], None] = '421ccd8d7753'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
# ### commands auto generated by Alembic - modified manually ###

        # Orders
    op.add_column(
            "orders",
            sa.Column(
                "total_price",
                sa.Float(),
                nullable=False,
                server_default="0.0"
            )
        )

        # Products
    op.add_column(
            "products",
            sa.Column(
                "quantity_unit",
                sa.String(length=20),
                nullable=True
            )
        )

        # Populate existing products
    op.execute("""
        UPDATE products
        SET quantity_unit = CASE
            WHEN id = 12 THEN 'pockets'
            ELSE 'pcs'
        END;
        """)
        # Make the column NOT NULL
    op.alter_column(
            "products",
            "quantity_unit",
            nullable=False
        )

        # Rename columns instead of dropping them
    op.alter_column(
            "products",
            "original_price",
            new_column_name="original_price_per_unit"
        )

    op.alter_column(
            "products",
            "discount_percentage",
            new_column_name="discount_percentage_per_unit"
        )

    op.alter_column(
            "products",
            "discounted_price",
            new_column_name="discounted_price_per_unit"
        )

        # Change quantity type
    op.alter_column(
            "products",
            "quantity",
            existing_type=sa.INTEGER(),
            type_=sa.Float(),
            existing_nullable=False
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.alter_column(
    "products",
    "original_price_per_unit",
    new_column_name="original_price"
)

    op.alter_column(
    "products",
    "discount_percentage_per_unit",
    new_column_name="discount_percentage"
)

    op.alter_column(
    "products",
    "discounted_price_per_unit",
    new_column_name="discounted_price"
)

    op.alter_column(
    "products",
    "quantity",
    existing_type=sa.Float(),
    type_=sa.Integer(),
    existing_nullable=False
)

    op.drop_column("products", "quantity_unit")

    op.drop_column("orders", "total_price")